name: DupeUtility
version: '3.0 ALPHA'
main: org.secvers.DupeUtility.SecVersDupe
api-version: '1.21'
load: STARTUP
authors: [ Mia_conmeow ]
description: Dupe Utility

commands:
  dupe:
    description: Basecommand for Dupe Utils
    usage: /dupe <reload|config>
    permission: dupeutils.command
    permission-message: You do not have permission to use this command.
  reload:
    description: Reloads Dupe Utils config
    usage: /dupe reload
    permission: dupeutils.reload
    permission-message: You do not have permission to use this command.
  config:
    description: Opens GUI to configure dupes allowed
    usage: /dupe config
    permission: dupeutils.configdupes
    permission-message: You do not have permission to use this command.