name: SecVerseDupeUtils
version: '2.0'
main: org.secverse.SecVerseDupeUtils.SecVersDupe
api-version: '1.21'
load: STARTUP
authors: [ Mia_conmeow ]
description: A custom SecVerse Dupe

commands:
  duperealod:
    description: Reloads SecVersDupeUtils config
    usage: /duperealod
    permission: dupeutils.reload
    permission-message: You do not have permission to use this command.
  configdupes:
    description: Opens GUI to configure dupes allowed
    usage: /configdupes
    permission: dupeutils.configdupes
    permission-message: You do not have permission to use this command.