name: SecVersDupe
version: '3.0'
main: org.secvers.DupeUtility.SecVersDupe
api-version: '1.21'
load: POSTWORLD
authors: [ SecVers ]
description: Advanced dupe and illegal item scanner

commands:
  dupe:
    description: DupeUtility management commands
    usage: /<command> [reload|config|economyfix]
    permission: dupeutils.command
    aliases: [dupeutil, du]

  economyfix:
    description: EconomyFix illegal items scanner
    usage: /<command> [scan|stats|toggle] [args]
    permission: economyfix.admin
    aliases: [efix, ef, illegalitems]

permissions:
  dupeutils.command:
    description: Base permission for dupe commands
    default: op
  dupeutils.reload:
    description: Reload plugin configuration
    default: op
  DupeUtility.configdupes:
    description: Access config GUI
    default: op
  economyfix.admin:
    description: Full access to EconomyFix commands
    default: op
  economyfix.notify:
    description: Receive notifications about illegal items
    default: op
